# Generated by Django 5.1.7 on 2025-05-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeacte',
            name='motif_demande',
        ),
        migrations.RemoveField(
            model_name='documentnumerique',
            name='cree_par',
        ),
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.commune'),
        ),
        migrations.AlterField(
            model_name='demandeacte',
            name='commune_traitement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commune'),
        ),
        migrations.AlterField(
            model_name='demandeacte',
            name='personne_concernee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personne'),
        ),
        migrations.AlterField(
            model_name='documentnumerique',
            name='type_document',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='logaudit',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
