# Generated by Django 5.1.7 on 2025-05-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_demandeacte_motif_demande_and_more'),
    ]

    operations = [
    ]
