# Generated by Django 5.1.7 on 2025-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demandeacte_montant_calcule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeacte',
            name='paiement_requis',
        ),
        migrations.AlterField(
            model_name='demandeacte',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total de la demande'),
        ),
    ]
