# Generated by Django 5.1.7 on 2025-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_demandeacte_paiement_requis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeacte',
            name='paiement_requis',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='demandeacte',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
