# Generated by Django 5.1.7 on 2025-05-27 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_photo_alter_user_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeacte',
            name='personne_concernee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_actes', to='core.personne'),
        ),
    ]
