# Generated by Django 5.1.7 on 2025-05-31 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_demandeacte_paiement_requis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='agent_confirmateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_confirmes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='code_erreur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_remboursement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='message_erreur',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_timbres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
