# Generated by Django 5.1.7 on 2025-05-27 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_demandeacte_personne_concernee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeacte',
            name='adresse_livraison',
            field=models.TextField(blank=True, verbose_name='Adresse de livraison (si applicable)'),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='agent_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Agent ayant validé la demande'),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='commentaire_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='date_validation_preliminaire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='justificatif_lien',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/lien/', verbose_name='Justificatif du lien de parenté'),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='lien_avec_personne',
            field=models.CharField(choices=[('LUI_MEME', 'Lui-même/Elle-même'), ('PERE', 'Père'), ('MERE', 'Mère'), ('ENFANT', 'Enfant'), ('CONJOINT', 'Conjoint(e)'), ('FRERE_SOEUR', 'Frère/Sœur'), ('REPRESENTANT_LEGAL', 'Représentant légal'), ('AUTRE', 'Autre')], default='LUI_MEME', max_length=50, verbose_name='Lien avec la personne concernée'),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='mode_retrait',
            field=models.CharField(choices=[('SUR_PLACE', 'Retrait sur place'), ('COURRIER', 'Envoi par courrier'), ('EMAIL', 'Envoi par email')], default='SUR_PLACE', max_length=15),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='montant_calcule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='motif_demande',
            field=models.CharField(choices=[('PERSONNEL', 'Usage personnel'), ('ADMINISTRATIVE', 'Démarche administrative'), ('JURIDIQUE', 'Procédure juridique'), ('SCOLAIRE', 'Inscription scolaire'), ('EMPLOI', "Recherche d'emploi"), ('AUTRE', 'Autre')], default='PERSONNEL', max_length=20),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='numero_suivi',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de suivi public'),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='paiement_requis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='piece_identite_demandeur',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/identite/', verbose_name="Pièce d'identité du demandeur"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='agent_confirmateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_confirmes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='code_erreur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_remboursement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='message_erreur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_timbres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personne',
            name='commune_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.commune', verbose_name='Commune de résidence actuelle'),
        ),
        migrations.AddField(
            model_name='personne',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='personne',
            name='est_vivant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='nationalite',
            field=models.CharField(default='Ivoirienne', max_length=50),
        ),
        migrations.AddField(
            model_name='personne',
            name='prenoms_mere',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénoms de la mère'),
        ),
        migrations.AddField(
            model_name='personne',
            name='prenoms_pere',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénoms du père'),
        ),
        migrations.AddField(
            model_name='personne',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{8,15}$', 'Numéro invalide')]),
        ),
        migrations.AlterField(
            model_name='demandeacte',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAIEMENT_CONFIRME', 'Paiement confirmé'), ('EN_COURS', 'En cours de traitement'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('DELIVRE', 'Délivré'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('CARTE_BANCAIRE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Échec'), ('EXPIRE', 'Expiré'), ('REMBOURSE', 'Remboursé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du père'),
        ),
    ]
