# Generated by Django 5.1.7 on 2025-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paiement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='code_erreur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_remboursement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='message_erreur',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_timbres',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
