# Generated by Django 5.1.7 on 2025-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_personne_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personne',
            unique_together={('email', 'telephone')},
        ),
        migrations.AddIndex(
            model_name='personne',
            index=models.Index(fields=['email'], name='core_person_email_05dc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='personne',
            index=models.Index(fields=['telephone'], name='core_person_telepho_7ef1c5_idx'),
        ),
    ]
