# Generated by Django 5.1.7 on 2025-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paiement_code_erreur_paiement_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('ECHEC', 'Échec'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
