# Generated by Django 5.1.7 on 2025-06-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_paiement_statut'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['statut'], name='core_demand_statut_98271c_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['date_demande'], name='core_demand_date_de_f23b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['commune_traitement', 'statut'], name='core_demand_commune_e7c79c_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('demande_acte',), name='unique_paiement_par_demande'),
        ),
    ]
