"""
Django settings for etat_civil_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# settings.py
import os
from dotenv import load_dotenv
from pathlib import Path
from django.conf import settings
from django.conf.urls.static import static

load_dotenv()

# Remplacer la ligne SECRET_KEY existante
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-uniquement-pour-dev')

APPEND_SLASH = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'jazzmin',  # Doit être avant django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # Notre application principale
    'rest_framework',
    'corsheaders',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap4',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Vos middlewares personnalisés
    'core.middleware.AdminRedirectMiddleware',
    'core.middleware.LoginRedirectMiddleware',
]

ROOT_URLCONF = 'etat_civil_ci.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

handler403 = 'core.views.erreur_403'
handler404 = 'core.views.erreur_404'
handler500 = 'core.views.erreur_500'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Abidjan'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration Jazzmin - CORRIGÉE
JAZZMIN_SETTINGS = {
    # Titre du site
    "site_title": "État Civil CI",
    "site_header": "Système de Gestion Intégré de l'État Civil",
    "site_brand": "État Civil",
    "site_logo": "images/logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "fas fa-certificate",
    
    # Message de bienvenue
    "welcome_sign": "Bienvenue dans le Système d'État Civil",
    "copyright": "République de Côte d'Ivoire - Ministère de l'Intérieur",
    
    # Recherche globale
    "search_model": ["auth.User", "core.DemandeActe", "core.Personne"],
    
    # Menu utilisateur
    "user_avatar": None,
    
    ############
    # Top Menu # - LIENS CORRIGÉS
    ############
    "topmenu_links": [
        # Utiliser des URLs Django admin existantes
        {"name": "Tableau de Bord", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Demandes", "url": "admin:core_demandeacte_changelist", "permissions": ["core.view_demandeacte"]},
        {"name": "Statistiques", "url": "admin:core_statistique_changelist", "permissions": ["core.view_statistique"]},
        {"name": "Utilisateurs", "url": "admin:core_user_changelist", "permissions": ["auth.view_user"]},
        {"app": "core"},
    ],

    #############
    # Menu Utilisateur #
    #############
    "usermenu_links": [
        {"name": "Support", "url": "https://support.gouv.ci", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Menu Latéral #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Ordre des apps dans le menu
    "order_with_respect_to": [
        "auth",
        "core.demandeacte",
        "core.personne", 
        "core.actenaissance",
        "core.mariage",
        "core.actedeces",
        "core.paiement",
        "core.commune",
        "core.statistique",
    ],

    # Icônes personnalisées pour les modèles
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Icônes pour vos modèles
        "core.demandeacte": "fas fa-file-alt",
        "core.personne": "fas fa-address-card",
        "core.actenaissance": "fas fa-baby",
        "core.mariage": "fas fa-heart",
        "core.actedeces": "fas fa-cross",
        "core.paiement": "fas fa-credit-card",
        "core.tarif": "fas fa-tags",
        "core.commune": "fas fa-city",
        "core.departement": "fas fa-map",
        "core.region": "fas fa-globe-africa",
        "core.statistique": "fas fa-chart-bar",
        "core.logaudit": "fas fa-history",
        "core.documentnumerique": "fas fa-file-pdf",
    },
    
    # Liens par défaut
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Liens connexes #
    #################
    "related_modal_active": False,

    #############
    # Interface utilisateur #
    #############
    "custom_css": None,  # Temporairement désactivé
    "custom_js": None,   # Temporairement désactivé
    
    # Utiliser Google Fonts
    "use_google_fonts_cdn": True,
    
    # Afficher la barre latérale sur les petits écrans
    "show_ui_builder": False,
    
    ############
    # Thème de changement #
    ############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "core.demandeacte": "horizontal_tabs",
        "core.personne": "vertical_tabs",
    },
    
    # Version sombre
    "theme": "default",
    
    # Personnalisation avancée
    "language_chooser": True,
}

# Configuration des UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-orange",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_accordion": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary", 
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

# Configuration REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Configuration CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Configuration Email (pour les notifications)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Pour le développement
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@etatcivil.ci')

# Configuration des logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'etat_civil': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

AUTH_USER_MODEL = 'core.User'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'

# Créer le dossier logs s'il n'existe pas
os.makedirs(BASE_DIR / 'logs', exist_ok=True)